spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lexblog
    username: lexblog
    password: lexblog
logging:
  level:
    liquidbase: INFO