spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.203:3306/lexblog
    username: lexblog
    password: lexblog
logging:
  level:
    liquidbase: INFO